[package]
name = "riscv-rs"
version = "0.1.0"
authors = ["Pekka Enberg <penberg@iki.fi>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
env_logger = "0.7"
goblin = "0.1"
log = "0.4"
memmap = "0.7"
quick-error = "1.2"
rangemap = "0.1"
structopt = "0.3"
